version: '3.8'

services:
  db:
    ports:
      - 5432:80
    image: postgres
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080