version: '3.8'

services:
  db:
    ports:
      - 5432:80
    image: postgres
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=password
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 3306:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db